# Generated by Django 5.1.2 on 2024-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="departments",
            field=models.ManyToManyField(
                related_name="affiliated_restaurants", to="restaurants.department"
            ),
        ),
    ]
