# Generated by Django 5.1.2 on 2024-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseplace", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="departments",
            field=models.ManyToManyField(
                related_name="affiliated_restaurants", to="baseplace.department"
            ),
        ),
    ]
