# Generated by Django 5.1.2 on 2024-10-29 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_restaurant_average_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
