# Generated by Django 5.1.2 on 2024-10-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0005_restaurant_latitude_restaurant_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="place_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
