# Generated by Django 5.1.2 on 2024-11-07 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0008_alter_restaurant_place_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="opening_hours",
        ),
    ]
