# Generated by Django 5.1.2 on 2024-11-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0010_restaurant_break_times"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=15, null=True
            ),
        ),
    ]
