# Generated by Django 5.1.2 on 2024-11-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0003_remove_customuser_recent_stamp_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="recent_stamp_cafes",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="recent_stamp_restaurants",
        ),
        migrations.AddField(
            model_name="customuser",
            name="recent_stamp_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="recent_stamp_object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
