# Generated by Django 5.1.2 on 2024-11-07 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_customuser_recent_stamp_cafes_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
