# Generated by Django 5.1.2 on 2024-11-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("stamps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stampedplace",
            name="category_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stamped_place_categories",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="stampedplace",
            name="category_object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
