# Generated by Django 5.1.2 on 2024-11-18 09:19

import meomeoknyang.asset_storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimage",
            name="image",
            field=models.ImageField(
                storage=meomeoknyang.asset_storage.MediaStorage(),
                upload_to="review_images/",
            ),
        ),
    ]
