# Generated by Django 5.1.2 on 2024-11-11 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_rename_object_id_review_place_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="place_type",
            new_name="content_type",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="place_id",
            new_name="object_id",
        ),
    ]
