# Generated by Django 5.1.2 on 2024-11-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("baseplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CafeCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("카공", "카공"),
                            ("디저트", "디저트"),
                            ("빵", "빵"),
                            ("테이크아웃", "테이크아웃"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cafe",
            fields=[
                ("place_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("contact", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("distance_from_gate", models.FloatField(blank=True, null=True)),
                ("open_date", models.DateField(blank=True, null=True)),
                ("average_price", models.IntegerField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=15, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=15, null=True
                    ),
                ),
                (
                    "break_times",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cafe_break_times",
                        to="baseplace.breaktime",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        related_name="affiliated_cafes", to="baseplace.department"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="cafes", to="cafe.cafecategory"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
