# Generated by Django 5.1.2 on 2024-10-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafecategory",
            name="name",
            field=models.CharField(
                choices=[("카공", "카공"), ("디저트", "디저트"), ("빵", "빵"), ("테이크아웃", "테이크아웃")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
