# Generated by Django 5.1.2 on 2024-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0003_cafe_break_times_cafe_operating_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="average_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
