# Generated by Django 5.1.2 on 2024-10-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0004_cafe_average_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
