# Generated by Django 5.1.2 on 2024-11-07 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0008_alter_cafe_place_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cafe",
            name="opening_hours",
        ),
        migrations.RemoveField(
            model_name="cafe",
            name="operating_hours",
        ),
    ]
