# Generated by Django 5.1.2 on 2024-11-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseplace", "0003_alter_breaktime_unique_together_and_more"),
        ("cafe", "0009_remove_cafe_opening_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="break_times",
            field=models.ManyToManyField(
                blank=True, related_name="cafe_break_times", to="baseplace.breaktime"
            ),
        ),
    ]
